name: Deploy Backend

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload backend to S3
        run: |
          aws s3 cp backend s3://${{ secrets.S3_BUCKET }}/backend --recursive

      - name: Deploy to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          # Guardar la clave SSH
          echo "$EC2_SSH_KEY" > ssh_key.pem
          chmod 600 ssh_key.pem
          
          # Conectar a EC2 y ejecutar el despliegue
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem $EC2_USERNAME@$EC2_HOST '
            # Descargar el código del backend desde S3
            aws s3 cp s3://${{ secrets.S3_BUCKET }}/backend /home/$EC2_USERNAME/backend --recursive
            
            # Navegar al directorio del backend
            cd /home/$EC2_USERNAME/backend
            
            # Instalar dependencias y construir
            npm install
            npm run build
            
            # Reiniciar la aplicación (asumiendo que usas PM2)
            pm2 restart backend || pm2 start dist/index.js --name backend
          '